spring.application.name=url-shortener
server.port=8082
server.forward-headers-strategy=framework

spring.data.mongodb.uri=${MONGO_URI:mongodb://127.0.0.1:27017/url-shortener-db}
spring.data.mongodb.auto-index-creation=true

spring.data.redis.url=${REDIS_URL:redis://127.0.0.1:6379}
